<?php

namespace Database\Seeders;

use App\Models\District;
use Illuminate\Database\Seeder;

class DistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $districts = [
            'Assam',
            'KAMRUP METROPOLITAN',
            'KAMRUP',
            'Sivasagar',
            'KOKRAJHAR',
            'DIBRUGARH',
            'Bholabari',
            'LAKHIMPUR',
            'Rajabari',
            'Simaluguri',
            'DHEMAJI',
            'North Lakhimpur',
            'Ratanpur',
            'Sonapur',
            'KARBI ANGLONG',
            'Nagaon',
            'Sibpur',
            'Bhalukmari',
            'Jamuguri',
            'Bargaon',
            'BARPETA',
            'Garukhuti',
            'MARIGAON',
            'SIBSAGAR',
            'Teliagaon',
            'Fulaguri',
            'Kanchanpur',
            'GOLAGHAT',
            'JORHAT',
            'TINSUKIA',
            'BONGAIGAON',
            'GOALPARA',
            'DHUBRI',
            'Guwahati',
            'East Garo Hills',
            'Kamrup',
            'South 24 Parganas',
            'BAKSA',
            'NALBARI',
            'KARIMGANJ',
            'CACHAR',
            'HAILAKANDI',
            'Baldabaldi',
            'Mohanpur',
            'Narainpur',
            'Katagaon',
            'Nimaichandpur',
            'Maniknagar',
            'Lowairpoa',
            'DIMA HASSO - NORTH CACHAR HILL',
            'Diyumbra',
            'Govindanagar',
            'DARRANG',
            'UDALGURI',
            'Ranipukhuri',
            'SONITPUR',
            'Tezpur',
            'Barika',
            'DIMAPUR',
            'Agartala',
            'EAST KHASI HILLS',
            'Shillong',
            'WEST TRIPURA',
            'SOUTH TRIPURA',
            'Silchar',
            'NORTH TRIPURA',
            'LOWER SUBANSIRI',
            'PAPUM PARE',
            'CHANGLANG',
            'Bishnupur',
            'Chandel',
            'Churachandpur',
            'Imphal West',
            'Jiribam',
            'Imphal East',
            'Thoubal',
            'Senapati',
            'Ukhrul',
            'Tengnoupal',
            'Tamenglong',
            'THANLON',
            'Aizawl',
            'Kolasib',
            'Lunglei',
            'Champhai',
            'Lawngtlai',
            'Serchhip',
            '"REC_ADDRESS1',
            'Mammit',
            'Phaileng',
            'Mamit',
            'Saiha',
            'Zunhebotto',
            'Mon',
            'Mokokchung',
            'Kohima',
            'Phek',
            'Kiphire',
            'Tuensang',
            'Longleng',
            'Zunheboto',
            'Peren',
            'Wokha',
            'Agartala ',
            'Sepahijala',
            'Gomati',
            'West Siang',
            'Dibang Valley',
            'Upper Dibang Valley',
            'West Kameng',
            'Lohit',
            'Upper Subansiri',
            'Tirap',
            'EAST SIANG',
            'Upper Siang',
            'Tawang',
            'Kurung Kumey',
            'Lower Dibang Valley',
            'East Kameng',
            'Dhalai',
            'Khowai',
            'Dharmanagar',
            'West Khasi Hills',
            'Ri Bhoi',
            'Jaintia Hills',
            'West Jaintia Hills',
            'East Jaintia Hills',
            'South West Khasi Hills',
            'Myriem',
            'Krang',
            'Mawlein Mawkhan',
            'West Garo Hills',
            'South Garo Hills',
            'abc',
            'Itanagar',
            'IMPHAL',
            'Aizawal',
            'Gomti',
            'Tura',
            'Churachanpur',
            'Kakching',
            'Kongpokpei',
            'Santir Bazar',
            'Bishalgarh',
            'RK Pur',
            'Pasighat',
            'Jairampur',
            'Bomdilla',
            'Kailashahar',
            'Teliamura',
            'Jowai',
            'Williamnagar',
            'HYDERABAD',
            'ADILABAD',
            'PRAKASAM',
            'NIRMAL',
            'NELLORE',
            'MANCHERIAL',
            'WARANGAL',
            'Hanamkonda',
            'West Godavari',
            'Jangaon',
            'Parkal',
            'BHUPALPALLI',
            'JAYASHANKAR',
            'KARIM NAGAR',
            'JAGTIAL',
            'KRISHNA',
            'GUNTUR',
            'SIRCILLA',
            'SIDDIPET',
            'PEDDAPALLI',
            'GADWAL',
            'MAHABUB NAGAR',
            'WANAPARTHY',
            'EAST GODAVARI',
            'VISAKHAPATNAM',
            'VIKARABAD',
            'RANGAREDDY',
            'MEDAK',
            'BHONGIR',
            'NALGONDA',
            'Purulia',
            'NIZAMABAD',
            'Vizianagaram',
            'Srikakulam',
            'Kamareddy',
            'Huzurabad',
            'SANGAREDDY',
            'KHAMMAM',
            'ZAHEERABAD',
            'SURYAPET',
            'Stn. Jadcherla',
            'NAGAR KURNOOL',
            'Hardoi',
            'Ranga Reddy',
            'Nagarkurnool',
            'MAHABUBABAD',
            'Mahabuababad',
            'Warangal Rural',
            'Trimulgherry',
            'Secunderabad',
            'K.V.Rangareddy',
            'KOTHAGUDEM',
            'KOTHAGUDEM COLLS',
            'BHADRACHALAM',
            'Mulugu',
            'Narsampet',
            'Kazipet',
            'ANANTHAPUR',
            'Anantapur',
            'Guntakal',
            'Chittoor',
            'Madanapalle',
            'KADAPA',
            'Cuddapah',
            'Dharmavaram',
            'Hindupur',
            'Kurnool',
            'Markapur',
            'Nandyal',
            'Proddatur',
            'Chandragiri',
            'Srikalahasti',
            'Bhimavaram',
            'Palakol',
            'Eluru',
            'Jangareddygudem',
            'Gudivada',
            'Gudur',
            'Mangalagiri',
            'Avanigadda',
            'Machilipatnam',
            'Narasaraopet',
            'Sattenapalle',
            'Kovvur',
            'Tadepalligudem',
            'Bapatla',
            'AMLAPURAM',
            'Bobbili',
            'Parvatipuram',
            'Vijayawada',
            'Ongole',
            'Tirupati',
            'Tirupathi',
            'YANAM',
            'Rajahmundry',
            'Karimnagar',
            'Mahabubnagar',
            'CHENNAI',
            'Bhainsa',
            'Bellampalli',
            'Sirpur Kagaznagar',
            'Mahbubnagar',
            'Deverkonda',
            'RAMAGUNDAM',
            'JAMMIKUNTA',
            'Zahirabad',
            'Shadnagar',
            'K.V.ranga reddy',
            'Palamaner',
            'Punganur',
            'Kadiri',
            'Penukonda',
            'Madakasira',
            'Adoni',
            'Dhone',
            'Nandikotkur',
            'Yemmiganur',
            'Tanuku',
            'Madhira',
            'Sathupalli',
            'Pamarru',
            'Nidadavole',
            'Tenali',
            'Repalle',
            'PATNA',
            'DARBHANGA',
            'Muzaffarpur',
            'Supaul',
            'Begusarai',
            'Khagaria',
            'Madhubani',
            'Sitamarhi',
            'Samastipur',
            'East Champaran',
            'Motihari',
            'Vaishali',
            'Katihar',
            'Kishanganj',
            'Purnia',
            'Araria',
            'Purnea',
            'Saharsa',
            'Madhepura',
            'Saran',
            'Bhojpur',
            'Siwan',
            'Sheohar',
            'NANPUR',
            'PARIHAR',
            'Gopalganj',
            'West Champaran',
            'Aurangabad(BH)',
            'Gaya',
            'AURANGABAD',
            'Arwal',
            'Jalaun',
            'Banka',
            'Bhagalpur',
            'Munger',
            'Buxar',
            'Jehanabad',
            'Jammui',
            'Jamui',
            'Lakhisarai',
            'Sheikhpura',
            'Nalanda',
            'Biharsharif',
            'Nawada',
            'NAWADHA',
            'D.G.TOLA',
            'FATEHPUR',
            'NANDLALABAD',
            'RUKUNPUR',
            'USFA',
            'Rohtas',
            'Kaimur (Bhabua)',
            'KAIMUR',
            'Hajipur',
            'BARAUNI',
            'CHAPRA',
            'NARKATIAGANJ',
            'ARA',
            'KIUL',
            'MOKAMA',
            'DEHRI-ON-SONE',
            'DEHRI ON SONE',
            'DEHRI',
            'Buxer',
            'Laheriasarai',
            'Aurangabad (BH)',
            'Alawalpur',
            'Muzzaffarpur',
            'Aurangabad (Bihar)',
            'Barsoi',
            'Mansi',
            'Sonepur',
            'Jamuai',
            'Bakhtiyarpur',
            'Sultanganj',
            'Jamalpur',
            'Dumraon',
            'A.N.Road',
            'Raipur',
            'Jagdalpur',
            'BASTAR',
            'Kanker',
            'Korba',
            'Janjgir-champa',
            'Bilaspur(CGH)',
            'Durg',
            'Rajnandgaon',
            'Bilaspur',
            'Ambikapur',
            'Raigarh',
            'Bijapur(CGH)',
            'Dantewada',
            'SUKMA',
            'KONDAGAON',
            'Narayanpur',
            'JANJGIR CHAMPA',
            'BALOD',
            'Kawardha',
            'Koriya',
            'Surguja',
            'Surajpur',
            'Jashpur',
            'Mahasamund',
            'Dhamtari',
            'GARIABAND',
            'Gohrapadar',
            'Makdi',
            'BIlaspur(CGH',
            'Bilaspur (Bilaspur-CGH)',
            'Poudi Uproda',
            'Kabirdham',
            'Korea',
            'Dipika',
            'BIJAPUR',
            'BHANUPRATAPPUR',
            'JANJGIR',
            'SAKTI',
            'JAMNIPALI',
            'PENDRA ROAD',
            'BHILAI',
            'BEMETARA',
            'JASHPUR NAGAR',
            'PATHALGAON',
            'BAIKUNTH',
            'BALODABAZAR',
            'NORTH DELHI',
            'Delhi',
            'East Delhi',
            'North West Delhi',
            'North East Delhi',
            'South Delhi',
            'South West Delhi',
            'WEST DELHI',
            'NEW DELHI',
            'Central Delhi',
            'Indraprastha',
            'South',
            'Ahmedabad',
            'Bhvanagar',
            'Banaskantha',
            'Gandhi Nagar',
            'Mahesana',
            'Patan',
            'Sabarkantha',
            'Amreli',
            'Rajkot',
            'Kachchh',
            'Surendra Nagar',
            'GANDHINAGAR',
            'Junagadh',
            'Bhavnagar',
            'Jamnagar',
            'Porbandar',
            'Diu',
            'Bhuj',
            'Surendranagar',
            'Anand',
            'Kheda',
            'The Dangs',
            'Surat',
            'Tapi',
            'Vadodara',
            'Navsari',
            'Narmada',
            'Bharuch',
            'Bilimora',
            'Dahod',
            'Panch Mahals',
            'Chhotaudepur',
            'Valsad',
            'Dadra & Nagar Haveli',
            'Daman',
            'Godhra',
            'Nadiad',
            'Dhola',
            'Himatnagar',
            'Mehsana',
            'Palanpur',
            'Godhara',
            'MEHASANA',
            'Morbi',
            'Nanpura',
            'RAJKOT.',
            'Deesa',
            'Tharad',
            'Deodar',
            'Dholka',
            'Dhandhuka',
            'Viramgam',
            'Kalol',
            'Chanasma',
            'Radhanpur',
            'Modasa',
            'Idar',
            'Bhiloda',
            'Bayad',
            'Lathi',
            'Dhari',
            'Rajula',
            'Gondal',
            'Khambhalia',
            'Veraval ( Gir Somnath)',
            'Una',
            'Bhachau',
            'Nakhtrana',
            'K-Mandvi',
            'Gandhidham',
            'Manavadar',
            'Limbdi',
            'Dhrangadhra',
            'Dakor',
            'Vadasinor',
            'Bardoli',
            'Ankleshwar',
            'Jambusar',
            'Jhagadia',
            'Rajpipla',
            'KAPADWANJ',
            'KHAMBHAT',
            'PETLAD',
            'Devgahbaria',
            'Halol',
            'Lunawada',
            'Santrampur',
            'Dabhoi',
            'Jetalsar',
            'Ambala',
            'Narnaul',
            'Sirsa',
            'JIND',
            'Sonipat',
            'Sonepat',
            'Ambala City',
            'PANCHKULA',
            'YAMUNANAGAR',
            'Bhiwani',
            'Faridabad',
            'Faridabad NIT',
            'Gurgaon',
            'REWARI',
            'MEWAT',
            'Mahendragarh',
            'Mahendergarh',
            'Hisar',
            'Fatehabad',
            'KARNAL',
            'PANIPAT',
            'KURUKSHETRA',
            'KAITHAL',
            'JHAJJAR',
            'Rohtak',
            'AMBALA CANTT',
            'Bahadurgarh',
            'Charkhi Dadri',
            'Tohana',
            'Bahadurgah',
            'Gohana',
            'MANDI',
            'Kangra',
            'Hamirpur(HP)',
            'Bilaspur (HP)',
            'Lahul & Spiti',
            'Kullu',
            'Shimla',
            'Kinnaur',
            'Sirmaur',
            'Solan',
            'Chamba',
            'HAMIRPUR',
            'Nahan',
            'RAMPUR',
            'PATHANKOT',
            'KALKA',
            'RAMPUR BUSHAHR',
            'Dehra',
            'Rampur Br.',
            'Rampur Bushar',
            'PATHANOT',
            'Dehra Gopipur',
            'DHARAMSHALA',
            'Jammu',
            'Baramulla',
            'Leh',
            'Rajouri',
            'Udhampur',
            'Kupwara',
            'Bandipur',
            'BANDIPORA',
            'Poonch',
            'Kathua',
            'Kargil',
            'Rajauri',
            'Reasi',
            'Ananthnag',
            'Shopian',
            'Anantnag',
            'Pulwama',
            'Kulgam',
            'Budgam',
            'Badgam',
            'Srinagar',
            'Ganderbal',
            'Doda',
            'RAMBAN',
            'KISHTWAR',
            'Samba',
            'SRI NAGAR',
            'Ranchi',
            'Bokaro',
            'Dhanbad',
            'Giridh',
            'Hazaribag',
            'Hazaribagh',
            'Koderma',
            'Chatra',
            'Ramgarh',
            'Garhwa',
            'Latehar',
            'Palamau',
            'Daltonganj',
            'Doranda',
            'Lohardaga',
            'West Singhbhum',
            'Gumla',
            'Simdega',
            'Khunti',
            'Godda',
            'Deoghar',
            'Dumka',
            'Pakur',
            'Jamtara',
            'Sahibganj',
            'Seraikela-kharsawan',
            'Chaibasa',
            'East Singhbhum',
            'Jamshedpur',
            'B.Deoghar',
            'Bokaro Steel City',
            'Gomoh',
            'Suriya',
            'Jasidih',
            'Jharkhand',
            'Saria',
            'Bengaluru',
            'Mysuru',
            'Manipal',
            'RAMANAGAR',
            'BAGALKOT',
            'BELAGAVI',
            'Belgaum',
            'HAVERI',
            'CHICKMAGALUR',
            'HASSAN',
            'Athani',
            'Jamkhandi',
            'Madikeri',
            'Ramdurg',
            'Kollegal',
            'Arsikere',
            'Kodagu',
            'Chikkamagaluru',
            'CHIKKABALLAPUR',
            'Bailhongal',
            'Sagar',
            'SHIVAMOGGA',
            'Tumakuru',
            'Bengaluru Rural',
            'Ramanagara',
            'Koppa',
            'Bilgi',
            'Vijayapura',
            'BELLARY',
            'Bellari',
            'DAVANGERE',
            'Kudligi',
            'Bidar',
            'Bhalki',
            'BIJAPUR(KAR)',
            'B.bagewadi',
            'Dharwad',
            'Hubballi',
            'Kundgol',
            'Kalghatgi',
            'GADAG',
            'KOPPAL',
            'KALABURAGI',
            'YADGIR',
            'UTTARA KANNADA',
            'RAICHUR',
            'Joida',
            'Siddapur',
            'Chitradurga',
            'Kolar',
            'Mandya',
            'Dakshina Kannada',
            'Udupi',
            'Saraswathipuram',
            'Hunsur',
            'Chamrajnagar',
            'CHAMARAJANAGAR',
            'Birur',
            'Bangarpet',
            'Mangaluru',
            'MANGALORE',
            'MYSORE',
            'SHIMOGA',
            'TUMKUR',
            'Bangalore',
            'SOLAPUR',
            'Ramanagaram',
            'Channapatna',
            'Sirsi',
            'DAVANAGERE',
            'MADIKERE',
            'H.A.L II Stage',
            'R T Nagar',
            'Hanagodu',
            'Nanjangud',
            'Ariskese',
            'HUMNABAD',
            'HUBLI',
            'Haliyal',
            'SOMWARPET',
            'VIRAJPET',
            'Krishnarajanagar',
            'NANAJANGUD',
            'T NARSIPURA',
            'KUNDAPURA',
            'Davengere',
            'Trivandrum',
            'Alappuzha',
            'Ernakulam',
            'Aluva',
            'Kottayam',
            'Idukki',
            'Pathanamthitta',
            'Kochi',
            'Lakshadweep',
            'Thodupuzha',
            'Thrissur',
            'Chalakudi',
            'Adur( Kla)',
            'Kollam',
            'Punalur',
            'Karunagappaly',
            'Kottarakara',
            'Thiruvananthapuram',
            'Attingal',
            'Kerala',
            'Poojapura',
            'Calicut',
            'Calicut Civil Station',
            'Kalpetta',
            'Kannur',
            'Taliparamba',
            'Kanhangad',
            'Kasaragod',
            'Malappuram',
            'Tirur',
            'Vadakara',
            'Manjeri-kla',
            'Ottapalam',
            'Koyilandi',
            'Alathur',
            'Olavakkot',
            'Palakkad',
            'Thalassery',
            'Ponani',
            'Kozhikode',
            'IRINJALAKUDA',
            'CHANGANASSERY',
            'KAYAMKULAM',
            'TIRUVALLA',
            'KASARGOD',
            'SHORANUR',
            'KASARAGODE',
            'Thiruvalla',
            'Perumbavoor',
            'ALAPPUZHA BAZAR',
            'KALLETTUMKARA',
            'Kozhikkode',
            'Wayanad',
            'BHOPAL',
            'INDORE',
            'Balaghat',
            'Mandla',
            'Seoni',
            'RAISEN',
            '237',
            'CHHATARPUR',
            'TIKAMGARH',
            'BETUL',
            'CHHINDWARA',
            'HOSHANGABAD',
            'NARSINGHPUR',
            'SATNA',
            'Damoh',
            'Sagar Cantt',
            'SHAHDOL',
            'UMARIA',
            'SIDHI',
            'VIDISHA',
            'Dewas',
            'DHAR',
            'JABALPUR',
            'Katni',
            'KHANDWA',
            'KHARGONE',
            'NEEMUCH',
            'JHABUA',
            'RATLAM',
            'RAJGARH',
            'SEHORE',
            'SHAJAPUR',
            'ASHOK NAGAR',
            'GUNA',
            'SHIVPURI',
            'Lashkar',
            'GWALIOR',
            'MORENA',
            'BHIND',
            'Dindori',
            'Bhopal G.P',
            'PANNA',
            'HARDA',
            'Sainkheda',
            'REWA',
            'ANUPPUR',
            'SINGRAULI',
            'BURHANPUR',
            'BARWANI',
            'East Nimar',
            'MANDSAUR',
            'ALIRAJPUR',
            'AGAR MALWA',
            'UJJAIN',
            'Ashoknagar',
            'DATIA',
            'SHEOPUR',
            'Itarsi',
            'Nagpur',
            'UJJIAN',
            'BINA',
            'Nainpur',
            'Maharashtra',
            'Mumbai',
            'Navi Mumbai',
            'Pune',
            'Chembur',
            'Chiplun',
            'RATNAGIRI',
            'Panvel',
            'RAIGARH(MH)',
            'BULDHANA',
            'Wardha',
            'SOUTH GOA',
            'NORTH GOA',
            'Panaji',
            'Kolhapur',
            'Ichalkaranji',
            'Kolhapur City',
            'Sindhudurg',
            'Sangli',
            'Andheri',
            'MUMBAI SUBUEBAN',
            'Thane',
            'Raigad',
            'Alibag',
            'Kalyan City',
            'PALGHAR',
            'AKOLA',
            'WASHIM',
            'Beed',
            'AMRAVATI',
            'Paratwada',
            'Buldana',
            'GADCHIROLI',
            'CHANDRAPUR',
            'BHANDARA',
            'GONDIA',
            'Nanded',
            'Yavatmal',
            'AHMED NAGAR',
            'SATARA',
            'Jalna',
            'Shrirampur',
            'Aurangabad (MH)',
            'Bhusawal',
            'Jalgaon',
            'Chalisgaon',
            'NANDURBAR',
            'DHULE',
            'JALGOAN',
            'Malegaon',
            'NASHIK',
            'LATUR',
            'Osmanabad',
            'HINGOLI',
            'PARBHANI',
            'AHMEDNAGAR',
            'MANMAD',
            'NASHIK ROAD',
            'KALYAN',
            'AURNAGABAD',
            ' NANDED',
            ' PARBHANI',
            ' BHUSAWAL',
            ' DHULE',
            ' JALGAON',
            ' NASHIK ROAD',
            'Miraj',
            'Borivali',
            'Bopodi',
            'Gadhinglaj',
            'Gargoti',
            'Jat',
            'U.Islampur',
            'Vite',
            'Pusad',
            'Wani',
            ' Pune',
            'Yawal',
            'Cuttack',
            'KHORDA',
            'Jagatsinghpur',
            'BALESWAR',
            'BALASORE',
            'BHADRAK',
            'KENDUJHAR',
            'Puri',
            'Bhubaneswar G.P',
            'Khurda',
            'JAJAPUR',
            'JAGATSINGHAPUR',
            'JAJPUR',
            'KENDRAPARA',
            'Kanpur',
            'MAYURBHANJ',
            'NABARANGAPUR',
            'NAYAGARH',
            'BALANGIR',
            'ANGUL',
            'DHENKANAL',
            'BARGARH',
            'JHARSUGUDA',
            'SAMBALPUR',
            'SUNDERGARH',
            'DEBAGARH',
            'DEOGARH',
            'KANDHAMAL',
            'GANJAM',
            'GAJAPATI',
            'KALAHANDI',
            'NUAPADA',
            'MALKANGIRI',
            'KORAPUT',
            'RAYAGADA',
            'Rayagada(K)',
            'BOUDH',
            'BHUBANESWAR',
            'HOWRAH',
            'Orissa',
            'Jajpur Road',
            'KEONJHAR',
            'Jeypore(K)',
            'Kapurthala',
            'Chandigarh',
            'LUDHIANA',
            'Punjab',
            'Batala',
            'Rupnagar',
            'Mohali',
            'Patiala',
            'Ropar',
            'Sangrur',
            'Jagraon',
            'Khanna',
            'Fatehgarh Sahib',
            'Rajpura',
            'Barnala',
            'Amritsar',
            'Tarn Taran',
            'Tarn',
            'Bathinda',
            'Mansa',
            'Muktsar',
            'Faridkot',
            'Moga',
            'Firozpur',
            'Ferozepur',
            'FAZILKA',
            'Gurdaspur',
            'Hoshiarpur',
            'Nawanshahr',
            'Dasuya',
            'Jalandhar',
            'Jalandhar Cantt',
            'Jalandhar City',
            'Phagwara',
            'U.T.',
            'Ludhiana (City)',
            '0395-Ludhiana',
            'JAIPUR',
            'AJMER',
            'Banswara',
            'Dungarpur',
            'JHALAWAR',
            'Kota',
            'Baran',
            'BUNDI',
            'TONK',
            'UDAIPUR',
            'Alwar',
            'BHARATPUR',
            'Dholpur',
            'Dausa',
            'Sawai Madhopur',
            'Karauli',
            'Barmer',
            'BIKANER',
            'CHURU',
            'JHUJHUNU',
            'Jaisalmer',
            'Jodhpur',
            'NAGAUR',
            'PALI',
            'Sikar',
            'JALOR',
            'SIROHI',
            'Hanumangarh',
            'SRI GANGANAGAR',
            'BHILWARA',
            'CHITTORGARH',
            'PRATAPGHAR',
            'RAJSAMAND',
            'Ganganagar',
            'Falna',
            'BANDIKUI',
            'SRIGANGANAGAR',
            'JHUNJHUNU',
            'Shastri Nagar',
            'Somesar',
            'Agra',
            'Rajasthan',
            'Bari',
            'Bayana',
            'chomu',
            'lalsot',
            'sambhar lake',
            'shahpura',
            'Gangapur',
            'Hindaun',
            'Sawaimadhopur',
            'Balotra',
            'Chohtan',
            'Pokran',
            'Neem Ka Thana',
            'Srimadhopur',
            'Merta Road',
            'KRISHNAGIRI',
            'Vellore',
            'Tiruvannamalai',
            'Kanchipuram',
            'Chengalpattu',
            'Tiruvallur',
            'Pondicherry',
            'Cuddalore',
            'Villupuram',
            'Tindivanam',
            'Ambattur',
            'Avadi Camp',
            'Tambaram',
            'Coimbatore',
            'Rathinasabapathy Puram',
            'DHARMAPURI',
            'Salem',
            'Erode',
            'Namakkal',
            'Karur',
            'NILGIRIS',
            'Tamilnadu',
            'Dindigul',
            'Suramangalam',
            'Dharapuram',
            'Mettupalayam',
            'Tirupur',
            'KANYAKUMARI',
            'SIVAGANGA',
            'RAMANATHAPURAM',
            'TUTICORIN',
            'TIRUNELVELI',
            'VIRUDHUNAGAR',
            'Sankarankovil',
            'Madurai',
            'Manamadurai',
            'THENI',
            'NAGAPATTINAM',
            'PERAMBALUR',
            'TIRUPPUR',
            'TIRUCHIRAPPALLI',
            'PUDUKKOTTAI',
            'THANJAVUR',
            'TIRUVARUR',
            'KARAIKAL',
            'ARIYALUR',
            'Turaiyur',
            'Kallakurichi',
            'Vriddhachalam',
            'Trichy',
            'Karaikudi',
            'Paramakudi',
            'Tenkasi',
            'Nagercoil',
            'Pollachi',
            'The Nilgiris',
            'Chidambaram',
            'Kumbakonam',
            'Mayiladuthurai',
            'Pudukottai',
            'Tirupapuliyur',
            'Virddhachalam',
            'Udagamandalam',
            'Nagarcoil',
            'Tirichirapalli',
            'Tiruchirapalli',
            'Vridhachalam',
            'Mayiladuturai',
            'RANIPET',
            'Bhavani',
            'Perundurai',
            'Coonoor',
            'Udumalpet',
            'Kovilpatti',
            'Palayankottai',
            'Rajapalayam',
            'Sivakasi',
            'Manapparai',
            'Kallakuruchi',
            'Ulundurpet',
            'Trichirapalli',
            'COIMABTORE',
            'SALEM JN',
            'CHIDAMBRAM',
            'AOB',
            'Arakkonam',
            'Jolarpettai',
            'KANCHEEPURAM',
            'Walajapet',
            'Madurantakam',
            'Sriperumbudur',
            'Tiruttani',
            'Mudaliarpet',
            'Gingee',
            'Arni',
            'Chengam',
            'Polur',
            'Vandavasi',
            'Palani',
            'Kodairoad R.S.',
            'Batlagundu',
            'Natham',
            'Vedasandur',
            'Madurai -2',
            'Melur',
            'Tirumangalam',
            'Vadipatti',
            'Velipattinam',
            'Mudukulathur',
            'Tiruvadanai',
            'Mana   madurai',
            'AMBASAMUDRAM',
            'VALLIOOR',
            'Aruppukottai.',
            'JC Puram',
            'Lalgudi',
            'Tirukoyilur',
            'Ul;undurpet',
            'vacant',
            'Lucknow',
            'Ghaziabad',
            'Noida',
            'Bulandshahr',
            'Bulandshahar',
            'Aligarh',
            'Khurja',
            'Etah',
            'Auraiya',
            'Etawah',
            'Lalitpur',
            'Orai',
            'Firozabad',
            'Mainpuri',
            'Mathura',
            'Pratapgarh',
            'Pilibhit',
            'Bijnor',
            'Dhampur',
            'Budaun',
            'Kheri',
            'Baraut',
            'Bagpat',
            'Meerut Cantt',
            'Meerut City',
            'Bareilly',
            'Amroha',
            'Allahabad',
            'Moradabad',
            'Muzaffarnagar',
            'Saharanpur',
            'Shahjahnapur',
            'Shahjahanpur',
            'Mau',
            'Ghazipur',
            'Ballia',
            'Rasra',
            'Varanasi Cantt',
            'Agra Fort',
            'SIDDHARTHNAGAR',
            'Varanasi',
            'Bansi',
            'Balrampur',
            'Banda',
            'Fatehgarh',
            'Farrukhabad',
            'Allahabad Kty.',
            'Mirzapur',
            'Unnao',
            'Barabanki',
            'Akbarpur',
            'Ambedkar Nagar',
            'Faizabad',
            'Hapur',
            'Jaunpur',
            'Lucknow Chowk',
            'Lalganj (Raebareli)',
            'Raebarely',
            'Sitapur',
            'Basti',
            'Jhansi',
            'Amethi',
            'Sultanpur',
            'Sultanpur (Avadh)',
            'Raebareli',
            'Hathras',
            'Gautam Buddha Nagar',
            'Azamgarh',
            'Kaushambi',
            'KUSHINAGAR',
            'Sonbhadra',
            'Chandauli',
            'Sant Ravidas Nagar',
            'Haridwar',
            'MEERUT',
            'BAGHPAT',
            'Jyotiba Phule Nagar',
            'Bahraich',
            'Shrawasti',
            'Sant Kabir Nagar',
            'Deoria',
            'Gonda',
            'Gorakhpur',
            'Maharajganj',
            'Kunraghat',
            'Chitrakoot',
            'Karwi',
            'Mahoba',
            'Kannauj',
            'Kanpur Nagar',
            'Kanpur Dehat',
            'Gautam Budh Nagar',
            'Yamuna Nagar',
            'KASGANJ',
            'Deoria Sadar',
            'Nazibabad',
            'Faizabad at Rly Station',
            'Raebareli at Rly Station',
            'Kheri at Rly Station',
            'Sultanpur at Rly Station',
            'Lucknow.',
            'Lucknow at Rly Station',
            'Manikpur',
            'Moghalsarai',
            'Ballia City',
            'TUNDLA',
            'KONCH',
            'GAZIPUR',
            'BHADOHI',
            'Najibabad',
            'Badaun',
            'PAURI',
            'Padrauna',
            'MAHARAGANJ',
            'Almora',
            'Ranikhet',
            'Gopeshwar',
            'Dehradun Cantt',
            'Dehradun',
            'Roorkee',
            'Haldwani',
            'Nainital',
            'Pauri Garhwal',
            'Kotdwara',
            'Lansdowne',
            'Pithoragarh',
            'Tehri',
            'Bageshwar',
            'Chamoli',
            'Rudraprayag',
            'Udham Singh Nagar',
            'USNAGAR',
            'Champawat',
            'Tehri Garhwal',
            'Uttarkashi',
            'KATHGODAM',
            'RUDARPRAYAG',
            'RUDARPUR',
            'Kotdwar',
            'Lansdown',
            'Pithoragah',
            'Dehradun G.P',
            'Rudrapur',
            'PITHORGARH',
            'KOLKATA',
            'North 24 Parganas',
            'Barasat',
            'Birbhum',
            'Suri',
            'Darjeeling',
            'Murshidabad',
            'Berhampore (WB)',
            'Kandi',
            'Raghunathganj',
            'Nadia',
            'Krishnanagar',
            'Nabadwip',
            'Barrackpore',
            '24Parganas(N)',
            'Belgharia',
            'Baruipur',
            'Diamond Harbour',
            'South Andaman',
            'North And Middle Andaman',
            'Nicobar',
            'Port Blair',
            'ALIPURDUAR',
            'Cooch Behar',
            'Kalimpong',
            'Darjiling',
            'Jalpaiguri',
            'HOOGHLY',
            'Malda',
            'North Sikkim',
            'East Sikkim',
            'West Sikkim',
            'Gangtok',
            'South Sikkim',
            'EAST',
            'South Dinajpur',
            'North Dinajpur',
            'Uttar Dinajpur',
            'Balurghat',
            'Dakshin Dinajpur',
            'Paschim Bardhaman',
            'Bardhaman',
            'Paschim  Bardhaman',
            'Burdwan',
            'Raniganj',
            'Bankura',
            'Bankua',
            'Purba Bardhaman',
            'East Midnapore',
            'PURBA MEDINIPUR',
            'West Midnapore',
            'Jhargram',
            'Midnapore',
            'PASCHIM MEDINIPUR',
            'Puruliya',
            'Siliguri',
            'DURGAPUR',
            'KHARAGPUR',
            'PANSKURA',
            'BERHAMPORE(WB',
            'RANAGHAT',
            'SAINTHIA',
            'Berhampore',
            'Berhampur',
            'Calcutta',
            'ALIPURDUAR  RMS',
            'MALDA  RMS',
            'DURGAPUR RMS',
            'BANKURA RMS',
            'KHARAGPUR RMS',
            'PURULIA RMS',
            'RANAGHAT RMS',
            'SAINTHIA RMS',
            'SEALDAH  RMS',
            'SEALDAH',
            'BERHAMPORE(WB)',
            'Pankura',
            '24 Prgs (South)',
            'Beleghata',
            'North 24 Pgs',
            'N 24 Parganas',
            'Medinipur',
            'Coochbehar',
            'Asansol',
            'A&N',
            '26 PGS(N)',
            '25 PGS(N)',
            '24 PGS(N)',
            'West Bardhaman',
        ];

        foreach ($districts as $district) {
            District::create([
                'name' => $district,
            ]);
        }
    }
}
